routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CitumController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\RecetumController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\ConsultumController;
use App\Http\Controllers\OdontologoController;
use App\Http\Controllers\TratamientoController;
use App\Http\Controllers\EspecialidadController;
use App\Http\Controllers\ReporteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::post('/citas/all', [CitumController::class, 'getAll']);

Route::group(['middleware' => ['auth']], function() {
    Route::prefix('admin')->group(function() {
        Route::get('recet/createFromConsulta/{consultaSeleccionadaId}', [RecetumController::class, 'createFromConsulta'])->name('recetacreateFromConsulta');
        Route::get('recet/verFromConsulta/{consultaSeleccionadaId}', [RecetumController::class, 'verFromConsulta'])->name('receta.showDeConsulta');
        Route::get('reporte/ConsultasPorMes', [ReporteController::class, 'ConsultasPorMes'])->name('rep.ConsultasPorMes');
        Route::get('reporte/generosDePaciente', [ReporteController::class, 'generosDePaciente'])->name('rep.generosDePaciente');
        Route::get('reporte/consultasPorTratamiento', [ReporteController::class, 'consultasPorTratamiento'])->name('rep.consultasPorTratamiento');
        Route::get('reporte/consultasPorPaciente', [ReporteController::class, 'consultasPorPaciente'])->name('rep.consultasPorPaciente');
        Route::get('reporte/consultasPorMesJSON', [ReporteController::class, 'consultasPorMesJSON'])->name('rep.ConsultasPorMes');

        Route::resource('citas', CitumController::class);
        Route::resource('receta', RecetumController::class);
        Route::resource('agendas', AgendaController::class);
        Route::resource('usuarios', UsuarioController::class);
        Route::resource('consulta', ConsultumController::class);
        Route::resource('pacientes', PacienteController::class);
        Route::resource('odontologos', OdontologoController::class);
        Route::resource('tratamientos', TratamientoController::class);
        Route::resource('especialidades', EspecialidadController::class);
        Route::get('menuEditar', function(){
            return  view('menu.edit');
        });
    });
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Especialidad.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;
/**
 * Class Especialidad
 *
 * @property $id
 * @property $nombre
 *
 * @property OdontologoEspecialidad[] $odontologoEspecialidads
 * @property Tratamiento[] $tratamientos
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Especialidad extends Model
{
    use SoftDeletes, Searchable;

    public function searchableAs()
    {
        return 'especialidad';
    }

    static $rules = [
    ];

    protected $table = 'Especialidad';

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['nombre'];

    public static function columns(): array {
        return Schema::getColumnListing('Especialidad');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function odontologoEspecialidads()
    {
        return $this->hasMany('App\Models\OdontologoEspecialidad', 'Especialidadid', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tratamientos()
    {
        return $this->hasMany('App\Models\Tratamiento', 'Especialidadid', 'id');
    }




}

app/Http/Controllers/EspecialidadController.php
<?php

namespace App\Http\Controllers;

use App\Models\Especialidad;
use Illuminate\Http\Request;

use App\Exports\EspecialidadExport;
use Maatwebsite\Excel\Facades\Excel;

/**
 * Class EspecialidadController
 * @package App\Http\Controllers
 */
class EspecialidadController extends Controller
{

    public function export() {
        return Excel::download(new EspecialidadExport(), 'especialidades.xlsx');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if($request->has('search')){

            $especialidads = Especialidad::search($request->search)

                ->paginate(6);

        }else{

            $especialidads = Especialidad::paginate(6);

        }

        return view('especialidad.index', compact('especialidads'))
            ->with('i', (request()->input('page', 1) - 1) * $especialidads->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $especialidad = new Especialidad();
        return view('especialidad.create', compact('especialidad'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Especialidad::$rules);

        $especialidad = Especialidad::create($request->all());

        return redirect()->route('especialidades.index')
            ->with('success', 'Especialidad created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $especialidad = Especialidad::find($id);

        return view('especialidad.show', compact('especialidad'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $especialidad = Especialidad::find($id);

        return view('especialidad.edit', compact('especialidad'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Especialidad $especialidad
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Especialidad $especialidad)
    {
        request()->validate(Especialidad::$rules);

        $especialidad->update($request->all());

        return redirect()->route('especialidades.index')
            ->with('success', 'Especialidad updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $especialidad = Especialidad::find($id)->delete();

        return redirect()->route('especialidades.index')
            ->with('success', 'Especialidad deleted successfully');
    }

    public function search()
    {
        // queries to Algolia search index and returns matched records as Eloquent Models
        $espe = Especialidad::search('title')->get();

        dd($espe);
    }
}

resources/views/especialidad/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Especialidad
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Especialidad</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('especialidades.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('especialidad.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/especialidad/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Especialidad
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Especialidad</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('especialidades.update', $especialidad->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('especialidad.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/especialidad/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('nombre') }}
            {{ Form::text('nombre', $especialidad->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            {!! $errors->first('nombre', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/especialidad/index.blade.php
@extends('layouts.app')

@section('template_title')
    Especialidad
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Especialidad') }}
                            </span>

                            <div>
                                <div class="float-right" style="margin-left: 5px">
                                    <a href="{{ route('especialidades.create') }}" class="btn btn-primary btn-sm float-right"
                                        data-placement="left">
                                        {{ __('Crear Nueva') }}
                                    </a>
                                </div>
                                <div class="float-right">
                                    <a href="{{ url('api/excel/especialidades') }}" class="btn btn-success btn-sm float-right"
                                        data-placement="left"
                                        download
                                    >
                                    📊 Excel
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>

                                        <th>Nombre</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($especialidads as $especialidad)
                                        <tr>
                                            <td>{{ ++$i }}</td>

                                            <td>{{ $especialidad->nombre }}</td>

                                            <td>
                                                <form action="{{ route('especialidades.destroy', $especialidad->id) }}"
                                                    method="POST">
                                                    <a title="show" class="btn btn-sm btn-primary "
                                                        href="{{ route('especialidades.show', $especialidad->id) }}"><i
                                                            class="fa fa-fw fa-eye"></i></a>
                                                    <a title="edit" class="btn btn-sm btn-success"
                                                        href="{{ route('especialidades.edit', $especialidad->id) }}"><i
                                                            class="fa fa-fw fa-edit"></i></a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button title="delete" type="submit" class="btn btn-danger btn-sm"><i
                                                            class="fa fa-fw fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $especialidads->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/especialidad/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $especialidad->name ?? 'Show Especialidad' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Especialidad</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('especialidades.index') }}"> Volver</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $especialidad->nombre }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection