routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CitumController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\RecetumController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\ConsultumController;
use App\Http\Controllers\OdontologoController;
use App\Http\Controllers\TratamientoController;
use App\Http\Controllers\EspecialidadController;
use App\Http\Controllers\ReporteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::post('/citas/all', [CitumController::class, 'getAll']);

Route::group(['middleware' => ['auth']], function() {
    Route::prefix('admin')->group(function() {
        Route::get('recet/createFromConsulta/{consultaSeleccionadaId}', [RecetumController::class, 'createFromConsulta'])->name('recetacreateFromConsulta');
        Route::get('recet/verFromConsulta/{consultaSeleccionadaId}', [RecetumController::class, 'verFromConsulta'])->name('receta.showDeConsulta');
        Route::get('reporte/ConsultasPorMes', [ReporteController::class, 'ConsultasPorMes'])->name('rep.ConsultasPorMes');
        Route::get('reporte/generosDePaciente', [ReporteController::class, 'generosDePaciente'])->name('rep.generosDePaciente');
        Route::get('reporte/consultasPorTratamiento', [ReporteController::class, 'consultasPorTratamiento'])->name('rep.consultasPorTratamiento');
        Route::get('reporte/consultasPorPaciente', [ReporteController::class, 'consultasPorPaciente'])->name('rep.consultasPorPaciente');
        Route::get('reporte/consultasPorMesJSON', [ReporteController::class, 'consultasPorMesJSON'])->name('rep.ConsultasPorMes');

        Route::resource('citas', CitumController::class);
        Route::resource('receta', RecetumController::class);
        Route::resource('agendas', AgendaController::class);
        Route::resource('usuarios', UsuarioController::class);
        Route::resource('consulta', ConsultumController::class);
        Route::resource('pacientes', PacienteController::class);
        Route::resource('odontologos', OdontologoController::class);
        Route::resource('tratamientos', TratamientoController::class);
        Route::resource('especialidades', EspecialidadController::class);
        Route::get('menuEditar', function(){
            return  view('menu.edit');
        });
    });
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Citum.php
<?php

namespace App\Models;

use Laravel\Scout\Searchable;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
/**
 * Class Citum
 *
 * @property $id
 * @property $horaInicio
 * @property $horaFin
 * @property $Pacienteid
 * @property $Agendaid
 * @property $created_at
 * @property $updated_at
 * @property $deleted_at
 *
 * @property Agenda $agenda
 * @property Consultum[] $consultas
 * @property Paciente $paciente
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Citum extends Model
{
    use SoftDeletes, Searchable;

    static $rules = [
		'horaInicio' => 'required',
		'horaFin' => 'required',
		'fecha' => 'required',
		'Pacienteid' => 'required',
		'Agendaid' => 'required',
    ];

    protected $perPage = 20;
    protected $table = 'Cita';
    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['horaInicio','horaFin','fecha','Pacienteid','Agendaid'];

    public static function columns(): array {
        return Schema::getColumnListing('Cita');
    }
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function agenda()
    {
        return $this->hasOne('App\Models\Agenda', 'id', 'Agendaid');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function consultas()
    {
        return $this->hasMany('App\Models\Consultum', 'Citaid', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function paciente()
    {
        return $this->hasOne('App\Models\Paciente', 'id', 'Pacienteid');
    }


}

app/Http/Controllers/CitumController.php
<?php

namespace App\Http\Controllers;

use App\Models\Citum;
use App\Models\Agenda;
use App\Models\Odontologo;
use Illuminate\Http\Request;

use App\Exports\CitumExport;
use Maatwebsite\Excel\Facades\Excel;
/**
 * Class CitumController
 * @package App\Http\Controllers
 */
class CitumController extends Controller
{
    public function export() {
        return Excel::download(new CitumExport(), 'citas.xlsx');
    }

    public function getAll($userId){


        $odontologoId=Odontologo::where('Usuarioid',$userId)->first()->id;

        $agendaIds=Agenda::where('Odontologoid',$odontologoId)->pluck('id');


        $citas=Citum::whereIn('Agendaid', $agendaIds)->get();
        //  \Log::info($citas->toJson());
        return $citas->toJson();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if($request->has('search')){

            $cita = Citum::search($request->search)

                ->paginate(6);

        }else{

            $cita = Citum::paginate(6);

        }

        return view('citum.index', compact('cita'))
            ->with('i', (request()->input('page', 1) - 1) * $cita->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $citum = new Citum();
        return view('citum.create', compact('citum'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Citum::$rules);

        $citum = Citum::create($request->all());

        return redirect()->route('citas.index')
            ->with('success', 'Citum created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $citum = Citum::find($id);

        return view('citum.show', compact('citum'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $citum = Citum::find($id);

        return view('citum.edit', compact('citum'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Citum $citum
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Citum $citum)
    {
        request()->validate(Citum::$rules);

        $citum->update($request->all());

        return redirect()->route('citas.index')
            ->with('success', 'Citum updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $citum = Citum::find($id)->delete();

        return redirect()->route('citas.index')
            ->with('success', 'Citum deleted successfully');
    }
}

resources/views/citum/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Citum
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Citum</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('citas.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('citum.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/citum/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Citum
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Citum</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('citas.update', $citum->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('citum.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/citum/form.blade.php
@php

use Illuminate\Support\Facades\Auth;
use \App\Http\Controllers\CitumController;
$citaCont=new CitumController()
 @endphp
 <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script>

    document.addEventListener('DOMContentLoaded', function() {
        // Evento de prueba
     var events=[  ]
  var citas=<?php echo json_encode( $citaCont->getAll(Auth::user()->id), JSON_HEX_TAG); ?>;
  citas=JSON.parse(citas)
  console.log(citas);
  for (const cita of citas) {
    var fechaCitaActual=cita.fecha;
    var tomorrow = new Date(fechaCitaActual);
    tomorrow.setDate((tomorrow.getDate()) + 1);
     console.log(fechaCitaActual,tomorrow.toISOString());
    events.push({ // this object will be "parsed" into an Event Object
      title: 'Cita', // a property!
      startRecur:  fechaCitaActual, // a property!
      endRecur: tomorrow.toISOString().split('T')[0], // a property! ** see important note below about 'end' **
      startTime: cita.horaInicio,
      endTime: cita.horaFin
    })
  }
  console.log(events);
        let draggableEl = document.getElementById('external-events');
        var  checkbox = document.getElementById('drop-remove');
      var calendarEl = document.getElementById('calendar');
      var calendar = new FullCalendar.Calendar(calendarEl, {
        events:events,
        initialView: 'timeGridWeek',
        headerToolbar: { center: 'dayGridMonth,timeGridWeek' }, // buttons for switching between views

        views: {
        dayGridMonth: { // name of view
            titleFormat: { year: 'numeric', month: '2-digit', day: '2-digit' }
            // other view-specific options here
        }},
        //  editable: true,
      droppable: true, // this allows things to be dropped onto the calendar
      drop: function(arg) {
        // is the "remove after drop" checkbox checked?
        if (checkbox.checked) {
          // if so, remove the element from the "Draggable Events" list
          arg.draggedEl.parentNode.removeChild(arg.draggedEl);
        }
      },
      });
      var Draggable = FullCalendar.Draggable;
      calendar.render();
      new Draggable(draggableEl, {
    itemSelector: '.fc-event',
    eventData: function(eventEl) {
      return {
        title: eventEl.innerText
      };
    }
  });
    });

  </script>

<style>

    body {
      margin-top: 40px;
      font-size: 14px;
      font-family: Arial, Helvetica Neue, Helvetica, sans-serif;
    }

    #wrap {
      width: 1100px;
      margin: 0 auto;
    }

    #external-events {
      float: left;
      width: 150px;
      padding: 0 10px;
      border: 1px solid #ccc;
      background: #eee;
      text-align: left;
    }

    #external-events h4 {
      font-size: 16px;
      margin-top: 0;
      padding-top: 1em;
    }

    #external-events .fc-event {
      margin: 10px 0;
      cursor: pointer;
    }

    #external-events p {
      margin: 1.5em 0;
      font-size: 11px;
      color: #666;
    }

    #external-events p input {
      margin: 0;
      vertical-align: middle;
    }

    #calendar {
      float: left;
      width: 100%;
    }

  </style>
<div class="box box-info padding-1">

    <div class="box-body">
      @php
        use App\Models\Paciente;
        use App\Models\Agenda;
      @endphp
        <div class="form-group">
            {{ Form::label('horaInicio') }}
            {{ Form::time('horaInicio', $citum->horaInicio, ['class' => 'form-control' . ($errors->has('horaInicio') ? ' is-invalid' : ''), 'placeholder' => 'Horainicio']) }}
            {!! $errors->first('horaInicio', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('horaFin') }}
            {{ Form::time('horaFin', $citum->horaFin, ['class' => 'form-control' . ($errors->has('horaFin') ? ' is-invalid' : ''), 'placeholder' => 'Horafin']) }}
            {!! $errors->first('horaFin', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
          {{ Form::label('Fecha') }}
          {{ Form::date('fecha', $citum->fecha, ['class' => 'form-control' . ($errors->has('fecha') ? ' is-invalid' : ''), 'placeholder' => 'fecha de cita']) }}
          {!! $errors->first('fecha', '<div class="invalid-feedback">:message</p>') !!}
      </div>
        <div class="form-group">
            {{ Form::label('Paciente') }}
            {{ Form::select('Pacienteid' ,Paciente::all()->pluck('nombre','id'),$citum->Pacienteid, ['class' => 'form-control' . ($errors->has('Pacienteid') ? ' is-invalid' : ''), 'placeholder' => 'Seleccione paciente']) }}
            {!! $errors->first('Pacienteid', '<div class="invalid-feedback">:message</p>') !!}
        </div>

        <div class="form-group">
            {{ Form::label('Agenda') }}
            {{ Form::select('Agendaid',Agenda::all()->pluck('nombre','id'),$citum->Agendaid, ['class' => 'form-control' . ($errors->has('Agendaid') ? ' is-invalid' : ''), 'placeholder' => 'Selecciona agenda']) }}
            {!! $errors->first('Agendaid', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

    {{-- <div id='external-events'>
        <p>
          <strong>Draggable Events</strong>
        </p>

        <div class='fc-event fc-h-event fc-daygrid-event fc-daygrid-block-event'>
          <div class='fc-event-main' data-event='{ "title": "my event", "duration": "05:00" }'>My Event 1</div>
        </div>
        <div class='fc-event fc-h-event fc-daygrid-event fc-daygrid-block-event'>
          <div class='fc-event-main'>My Event 2</div>
        </div>


        <p>
          <input type='checkbox' id='drop-remove' />
          <label for='drop-remove'>remove after drop</label>
        </p>
      </div> --}}
      <h5>Horarios de Citas</h5>
      <div id='calendar'></div>
</div>

resources/views/citum/index.blade.php
@extends('layouts.app')

@section('template_title')
    Citas
@endsection
@php
use App\Models\Paciente;
use App\Models\Agenda;

@endphp
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Citas') }}
                            </span>

                            <div>
                                <div class="float-right" style="margin-left: 5px">
                                    <a href="{{ route('citas.create') }}" class="btn btn-primary btn-sm float-right"
                                        data-placement="left">
                                        {{ __('Crear Nueva') }}
                                    </a>
                                </div>
                                <div class="float-right">
                                    <a href="{{ url('api/excel/citas') }}" class="btn btn-success btn-sm float-right"
                                        data-placement="left"
                                        download
                                    >
                                        📊 Excel
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>

                                        <th>Horainicio</th>
                                        <th>Horafin</th>
                                        <th>fecha</th>
                                        <th>Paciente</th>
                                        <th>Agendaid</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($cita as $citum)
                                        <tr>
                                            <td>{{ ++$i }}</td>

                                            <td>{{ $citum->horaInicio }}</td>
                                            <td>{{ $citum->horaFin }}</td>
                                            <td>{{ $citum->fecha }}</td>
                                            <td>{{ Paciente::where('id', $citum->Pacienteid)->pluck('nombre')->first() }}
                                            </td>
                                            <td>{{ Agenda::where('id', $citum->Agendaid)->pluck('nombre')->first() }}</td>

                                            <td>
                                                <form action="{{ route('citas.destroy', $citum->id) }}" method="POST">
                                                    <a title="show" class="btn btn-sm btn-primary "
                                                        href="{{ route('citas.show', $citum->id) }}"><i
                                                            class="fa fa-fw fa-eye"></i></a>
                                                    <a title="edit" class="btn btn-sm btn-success"
                                                        href="{{ route('citas.edit', $citum->id) }}"><i
                                                            class="fa fa-fw fa-edit"></i></a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button title="delete" type="submit" class="btn btn-danger btn-sm"><i
                                                            class="fa fa-fw fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $cita->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/citum/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $citum->name ?? 'Show Citum' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Citum</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('citas.index') }}"> Atras</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Horainicio:</strong>
                            {{ $citum->horaInicio }}
                        </div>
                        <div class="form-group">
                            <strong>Horafin:</strong>
                            {{ $citum->horaFin }}
                        </div>
                        <div class="form-group">
                            <strong>Pacienteid:</strong>
                            {{ $citum->Pacienteid }}
                        </div>
                        <div class="form-group">
                            <strong>Agendaid:</strong>
                            {{ $citum->Agendaid }}
                        </div>
                        <div class="form-group">
                            <strong>Fecha:</strong>
                            {{ $citum->fecha }}
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection