routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CitumController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\RecetumController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\ConsultumController;
use App\Http\Controllers\OdontologoController;
use App\Http\Controllers\TratamientoController;
use App\Http\Controllers\EspecialidadController;
use App\Http\Controllers\ReporteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::post('/citas/all', [CitumController::class, 'getAll']);

Route::group(['middleware' => ['auth']], function() {
    Route::prefix('admin')->group(function() {
        Route::get('recet/createFromConsulta/{consultaSeleccionadaId}', [RecetumController::class, 'createFromConsulta'])->name('recetacreateFromConsulta');
        Route::get('recet/verFromConsulta/{consultaSeleccionadaId}', [RecetumController::class, 'verFromConsulta'])->name('receta.showDeConsulta');
        Route::get('reporte/ConsultasPorMes', [ReporteController::class, 'ConsultasPorMes'])->name('rep.ConsultasPorMes');
        Route::get('reporte/generosDePaciente', [ReporteController::class, 'generosDePaciente'])->name('rep.generosDePaciente');
        Route::get('reporte/consultasPorTratamiento', [ReporteController::class, 'consultasPorTratamiento'])->name('rep.consultasPorTratamiento');
        Route::get('reporte/consultasPorPaciente', [ReporteController::class, 'consultasPorPaciente'])->name('rep.consultasPorPaciente');
        Route::get('reporte/consultasPorMesJSON', [ReporteController::class, 'consultasPorMesJSON'])->name('rep.ConsultasPorMes');

        Route::resource('citas', CitumController::class);
        Route::resource('receta', RecetumController::class);
        Route::resource('agendas', AgendaController::class);
        Route::resource('usuarios', UsuarioController::class);
        Route::resource('consulta', ConsultumController::class);
        Route::resource('pacientes', PacienteController::class);
        Route::resource('odontologos', OdontologoController::class);
        Route::resource('tratamientos', TratamientoController::class);
        Route::resource('especialidades', EspecialidadController::class);
        Route::get('menuEditar', function(){
            return  view('menu.edit');
        });
    });
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Odontologo.php
<?php

namespace App\Models;

use Laravel\Scout\Searchable;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
/**
 * Class Odontologo
 *
 * @property $id
 * @property $ci
 * @property $nombre
 * @property $fNac
 * @property $celular
 * @property $genero
 * @property $Usuarioid
 *
 * @property Agenda[] $agendas
 * @property OdontologoEspecialidad $odontologoEspecialidad
 * @property Usuario $usuario
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Odontologo extends Model
{
    use Searchable;

    static $rules = [
		'ci' => 'required',
		'nombre' => 'required',
		'fNac' => 'required',
		'genero' => 'required',
		'Usuarioid' => 'required',
    ];

    protected $perPage = 20;
    protected $table = 'Odontologo';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['ci','nombre','fNac','celular','genero','Usuarioid'];

    public static function columns(): array {
        return Schema::getColumnListing('Odontologo');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function agendas()
    {
        return $this->hasMany('App\Models\Agenda', 'Odontologoid', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function odontologoEspecialidad()
    {
        return $this->hasOne('App\Models\OdontologoEspecialidad', 'Odontologoid', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function usuario()
    {
        return $this->hasOne('App\Models\Usuario', 'id', 'Usuarioid');
    }


}

app/Http/Controllers/OdontologoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Odontologo;
use Illuminate\Http\Request;

use App\Exports\OdontologoExport;
use Maatwebsite\Excel\Facades\Excel;

/**
 * Class OdontologoController
 * @package App\Http\Controllers
 */
class OdontologoController extends Controller
{
    public function export() {
        return Excel::download(new OdontologoExport(), 'odontologos.xlsx');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if($request->has('search')){

            $odontologos = Odontologo::search($request->search)

                ->paginate(6);

        }else{

            $odontologos = Odontologo::paginate(6);

        }

        return view('odontologo.index', compact('odontologos'))
            ->with('i', (request()->input('page', 1) - 1) * $odontologos->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $odontologo = new Odontologo();
        return view('odontologo.create', compact('odontologo'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Odontologo::$rules);

        $odontologo = Odontologo::create($request->all());

        return redirect()->route('odontologos.index')
            ->with('success', 'Odontologo created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $odontologo = Odontologo::find($id);

        return view('odontologo.show', compact('odontologo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $odontologo = Odontologo::find($id);

        return view('odontologo.edit', compact('odontologo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Odontologo $odontologo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Odontologo $odontologo)
    {
        request()->validate(Odontologo::$rules);

        $odontologo->update($request->all());

        return redirect()->route('odontologos.index')
            ->with('success', 'Odontologo updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $odontologo = Odontologo::find($id)->delete();

        return redirect()->route('odontologos.index')
            ->with('success', 'Odontologo deleted successfully');
    }
}

resources/views/odontologo/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Odontologo
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Odontologo</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('odontologos.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('odontologo.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/odontologo/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Odontologo
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Odontologo</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('odontologos.update', $odontologo->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('odontologo.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/odontologo/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">

        <div class="form-group">
            {{ Form::label('ci') }}
            {{ Form::number('ci', $odontologo->ci, ['class' => 'form-control' . ($errors->has('ci') ? ' is-invalid' : ''), 'placeholder' => 'Ci']) }}
            {!! $errors->first('ci', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('nombre') }}
            {{ Form::text('nombre', $odontologo->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            {!! $errors->first('nombre', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('fNac') }}
            {{ Form::date('fNac', $odontologo->fNac, ['class' => 'form-control' . ($errors->has('fNac') ? ' is-invalid' : ''), 'placeholder' => 'Fnac']) }}
            {!! $errors->first('fNac', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('celular') }}
            {{ Form::number('celular', $odontologo->celular, ['class' => 'form-control' . ($errors->has('celular') ? ' is-invalid' : ''), 'placeholder' => 'Celular']) }}
            {!! $errors->first('celular', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('genero') }}
            {{ Form::select('genero', array('M' => 'Masculino', 'F' => 'Femenino'), $odontologo->genero, ['class' => 'form-control' . ($errors->has('genero') ? ' is-invalid' : ''), 'placeholder' => 'Genero']) }}
            {!! $errors->first('genero', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        @php
             use App\Models\User;
        @endphp
        <div class="form-group">
            {{ Form::label('Email de usuario') }}
            {{ Form::select('Usuarioid',User::all()->pluck('email','id'), $odontologo->Usuarioid, ['class' => 'form-control' . ($errors->has('Usuarioid') ? ' is-invalid' : ''), 'placeholder' => 'Usuarioid']) }}
            {!! $errors->first('Usuarioid', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/odontologo/index.blade.php
@extends('layouts.app')

@section('template_title')
    Odontologo
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Odontologo') }}
                            </span>
                            <div>
                                <div class="float-right" style="margin-left: 5px">
                                    <a href="{{ route('odontologos.create') }}" class="btn btn-primary btn-sm float-right"
                                        data-placement="left">
                                        {{ __('Crear Nueva') }}
                                    </a>
                                </div>
                                <div class="float-right">
                                    <a href="{{ url('api/excel/odontologos') }}" class="btn btn-success btn-sm float-right" 
                                        data-placement="left"
                                        download
                                    >
                                        📊 Excel
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>

                                        <th>Ci</th>
                                        <th>Nombre</th>
                                        <th>Fnac</th>
                                        <th>Celular</th>
                                        <th>Genero</th>
                                        {{-- Equivalente a usuarioid: --}}
                                        <th>Email de Usuario</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        use App\Models\User;
                                    @endphp
                                    @foreach ($odontologos as $odontologo)
                                        <tr>
                                            <td>{{ ++$i }}</td>

                                            <td>{{ $odontologo->ci }}</td>
                                            <td>{{ $odontologo->nombre }}</td>
                                            <td>{{ $odontologo->fNac }}</td>
                                            <td>{{ $odontologo->celular }}</td>
                                            <td>{{ $odontologo->genero }}</td>
                                            <td>{{ User::where('id', $odontologo->Usuarioid)->pluck('email')->first() }}
                                            </td>

                                            <td>
                                                <form action="{{ route('odontologos.destroy', $odontologo->id) }}"
                                                    method="POST">
                                                    <a title="show" class="btn btn-sm btn-primary "
                                                        href="{{ route('odontologos.show', $odontologo->id) }}"><i
                                                            class="fa fa-fw fa-eye"></i></a>
                                                    <a title="edit" class="btn btn-sm btn-success"
                                                        href="{{ route('odontologos.edit', $odontologo->id) }}"><i
                                                            class="fa fa-fw fa-edit"></i></a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button title="delete" type="submit" class="btn btn-danger btn-sm"><i
                                                            class="fa fa-fw fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $odontologos->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/odontologo/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $odontologo->name ?? 'Show Odontologo' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Odontologo</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('odontologos.index') }}"> Volver</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Ci:</strong>
                            {{ $odontologo->ci }}
                        </div>
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $odontologo->nombre }}
                        </div>
                        <div class="form-group">
                            <strong>Fnac:</strong>
                            {{ $odontologo->fNac }}
                        </div>
                        <div class="form-group">
                            <strong>Celular:</strong>
                            {{ $odontologo->celular }}
                        </div>
                        <div class="form-group">
                            <strong>Genero:</strong>
                            {{ $odontologo->genero }}
                        </div>
                        <div class="form-group">
                            <strong>Usuarioid:</strong>
                            {{ $odontologo->Usuarioid }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection